### ISSUE TITLE
PR: Catch Multiple Errors

### ISSUE THREAD

**Issue by KyleKing** [mortymacs/abcmeta#4]
Would you be open to a PR that catches multiple errors and prints them all at once?

I was thinking that instead of the `raise AttributeError()`, the errors could be collected and then raised at the end

https://github.com/mortymacs/abcmeta/blob/4fef29bdc78b52830b9431d93f66cdccee1adf9b/abcmeta/__init__.py#L157-L187

Could be modified like this:

```py
errors = []
for name, obj in vars(cls.__base__).items():
    ...
    if name not in cls.__dict__:
        errors.append(
            "Derived class '{}' has not implemented '{}' method of the"
            " parent class '{}'.".format(
                cls.__name__, name, cls.__base__.__name__
            )
        )
        continue
    ...
if errors:
    raise AttributeError("\n\n".join(errors))
```

**Comment by mortymacs** [comment]
Hi Kyle,

That's an excellent idea! :+1: 
Would you please send a PR, or I prepare it myself?

**Comment by KyleKing** [comment]
Submitting now! Just adding a new test

**Comment by mortymacs** [comment]
Hi Kyle,

I just released the new version. Please check it and let me know if there is anything you need. :)

Cheers,
Mort

**Comment by KyleKing** [comment]
Perfect, thanks! The Windows support and error index are really nice additions
